// <auto-generated />
namespace WebAPISample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addeseeddatatodb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeseeddatatodb));
        
        string IMigrationMetadata.Id
        {
            get { return "201909111507041_adde-seed-data-to-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
